config/routes.rb
Rails.application.routes.draw do

 
  resources :advertisements
  resources :topics do
   resources :posts, except: [:index]
   resources :sponsored_post
  end
  resources :questions
  
  resources :users, only: [:new, :create]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  post 'users/confirm' => 'users#confirm'
  

  get 'about' => 'welcome#about'
  
  

  root to: 'welcome#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
   belongs_to :topic
   has_many :comments, dependent: :destroy
   
   validates :title, length: { minimum: 5 }, presence: true
   validates :body, length: { minimum: 20 }, presence: true
   validates :topic, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
#  def index
#    @posts = Post.all
#  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end
  
  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])
    @post.topic = @topic
    
    if @post.save
      flash[:notice] = "Post was saved"
#      redirect_to @post
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error sainv the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
   @post = Post.find(params[:id])
   @post.title = params[:post][:title]
   @post.body = params[:post][:body]
   
   if @post.save
    flash[:notice] = "Post was updated."
#    redirect_to @post
    redirect_to [@post.topic, @post]
   else
    flash.now[:alert] = "There was an error saving the post. Please try again."
    render :edit
   end
  end
  
  def destroy
     @post = Post.find(params[:id])
 
     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
#       redirect_to posts_path
       redirect_to @post.topic
     else
       flash.now[:alert] = "There was an error deleting the post."
       render :show
     end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@post.topic, @post] do |f| %>
 <% if post.errors.any? %>
 <div class="alert alert-danger">
  <h4><%= pluralize(post.errors.count, "error")%>.</h4>
  <ul>
   <% post.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
  </ul>
 </div>
 <% end %>
 
 <%= form_group_tag(post.errors[:title]) do %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
 <% end %>
 
 <%= form_group_tag(post.errors[:body]) do %> 
  <%= f.label :body %>
  <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
 <% end %>
 
 <div class="form-group">
  <%= f.submit "Save", class: 'btn btn-success' %>
 </div>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
   </div>
 </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

  <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
  
   <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>
  </div>
 

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= @post.body %></p>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
     <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
   </div>
 </div>