config/routes.rb
Rails.application.routes.draw do

 
  resources :advertisements
  resources :topics do
   resources :posts, except: [:index]
   resources :sponsored_post
  end
  resources :questions
  
  resources :users, only: [:new, :create]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  post 'users/confirm' => 'users#confirm'
  

  get 'about' => 'welcome#about'
  
  

  root to: 'welcome#index'
  

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
   belongs_to :topic
   has_many :comments, dependent: :destroy
   
   validates :title, length: { minimum: 5 }, presence: true
   validates :body, length: { minimum: 20 }, presence: true
   validates :topic, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
    has_many :answers
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
   has_many :posts
   has_many :sponsored_posts
   
   validates :name, length: { minimum: 5 }, presence: true
   validates :description, length: { minimum: 15 }, presence: true
   # validates :topic, presence: true
   
end

app/models/user.rb
class User < ActiveRecord::Base
 # #2
   before_save { self.email = email.downcase }
   before_save :format_name
 # #3
   EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 # #4
   validates :name, length: { minimum: 1, maximum: 100 }, presence: true
 # #5
  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true
 # #6
   validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 100 },
             format: { with: EMAIL_REGEX }
 # #7
   has_secure_password
   
   def format_name
       if name 
           name_array = []
           name.split.each do |name_part|
               name_array << name_part.capitalize
           end
           
        self.name = name_array.join("")
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
#  def index
#    @posts = Post.all
#  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end
  
  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])
    @post.topic = @topic
    
    if @post.save
      flash[:notice] = "Post was saved"
#      redirect_to @post
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error sainv the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
   @post = Post.find(params[:id])
   @post.title = params[:post][:title]
   @post.body = params[:post][:body]
   
   if @post.save
    flash[:notice] = "Post was updated."
#    redirect_to @post
    redirect_to [@post.topic, @post]
   else
    flash.now[:alert] = "There was an error saving the post. Please try again."
    render :edit
   end
  end
  
  def destroy
     @post = Post.find(params[:id])
 
     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
#       redirect_to posts_path
       redirect_to @post.topic
     else
       flash.now[:alert] = "There was an error deleting the post."
       render :show
     end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
 def index
  @topics = Topic.all
 end
    
 def show
  @topic = Topic.find(params[:id])
 end
    
 def new
  @topic = Topic.new
 end
 
 def create
  @topic = Topic.new
  @topic.name = params[:topic][:name]
  @topic.description = params[:topic][:description]
  @topic.public = params[:topic][:public]
    
  if @topic.save
   redirect_to @topic, notice: "Topic was saved successfully."
  else
   flash.now[:alert] = "Error creating topic. Please try again."
   render :new
  end
 end
 
 def update
  @topic = Topic.find(params[:id])
  
  @topic.name = params[:topic][:name]
  @topic.description = params[:topic][:description]
  @topic.public = params[:topic][:public]
  
  if @topic.save
   flash[:notice] = "Topic was updated."
   redirect_to @topic
  else
   flash.now[:alert] = "Error saving topic. Please try again."
   render :edit
  end
 end
 
 def edit
  @topic = Topic.find(params[:id])
 end
 
 def destroy
  @topic = Topic.find(params[:id])
  
  if @topic.destroy
   flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
   redirect_to action: :index
  else
   flash.now[:alert] = "There was an error deleting the topic."
   render :show
  end
 end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def confirm
        @user = User.new
        @user.name = params[:user][:name]
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password_confirmation]
    end    
    
    def create
        @user = User.new
        @user.name = params[:user][:name]
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password_confirmation]
        
        if @user.save
            flash[:notice] = "Welcome to Bloccit #{@user.name}!"
            create_session(@user)
            redirect_to root_path
        else
            flash.now[:alert] = "There was an error creating your account. Please try again."
            render :new
        end
    end    
        
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
 def form_group_tag(errors, &block)
     if errors.any?
         content_tag :div, capture(&block), class: 'form-group has-error'
     else
         content_tag :div, capture(&block), class: 'for-group'
     end
 end
 
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def create_session(user)
     session[:user_id] = user.id
   end
 
 # #5
   def destroy_session(user)
     session[:user_id] = nil
   end
 
 # #6
   def current_user
     User.find_by(id: session[:user_id])
   end
end

app/helpers/sponsored_post_helper.rb
module SponsoredPostHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/confirm/confirm.html.erb
<h2>Sign up Confirmation</h2>

<div class="row">
 <div class="col-nd-4">
  <h3>Are you sure these values are correct?</h3>
  <h4>Email: <%@user.email%></h4>
  <h5>User:<%@user.name%></h5>
 </div>
</div>

<div class="row">
 <div class="col-nd-4", styles"width: auto">
  <%= button_to "Yes", {controller: "users", action: "create", params: params}, class: 'btn btn-success' %>
 </div>
</div>

<div class="row">
 <div class="col-nd-4", styles"width: auto">
  <%= button_to "No", {controller: "users", action: "new"}, class: 'btn btn-failure' :method => :get %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
  <head>
   <title>Bloccit</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
  </head>
  
  <body>
   <div class="container">
     <ul class="nav nav-tabs">
       <li><%= link_to "Bloccit", root_path %></li>
       <li><%= link_to "Topics", topics_path %></li>
       <li><%= link_to "About", about_path %></li>
       <li><%= link_to "Questions", questions_path %></li>
       
       <div class="pull-right user-info">
        <%= link_to "Sign Up", new_user_path %>
       </div>
     </ul>
 
     <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:error] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:error] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>

     <%= yield %>
   </div>
  </body>
  
 </html>